openapi: 3.0.0
paths:
  /api/posts/:
    get:
      summary: List all posts
      tags: [Posts]
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          required: false
        - name: offset
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Return list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
      security: []
    post:
      summary: Create a new post
      tags: [Posts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        '201':
          description: Post created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      security:
        - CookieAuth: []
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        text:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        likes_count:
          type: integer
        comments_count:
          type: integer
